### ISSUE TITLE
Something about optimze

### ISSUE THREAD

**Issue by DemonCloud** [fiduswriter/diffDOM#53] opened 2017-04-06 02:22 UTC
swap object method can write as
dont use closure
```
function swap(obj,a,b){
       obj[a]^=obj[b];
       obj[b]^=obj[a];
       obj[a]^=obj[b];
}
```

another optimze : 
dont use forEach method for the Array, because it create self-block scope
https://jsperf.com/for-vs-foreach/75

**Comment by ansuz** [comment] 2017-04-06 07:00
are `a` and `b` guaranteed to be integers in every usage of this function?

**Comment by DemonCloud** [comment] 2017-04-06 07:10
@ansuz 
The primitive variable can not use this swap method. because in `function(a,b)`, `a` and `b` are calling by reference(quote).  but Object is pointer variable. 
So u cant write it as:
```
function(a,b){
   a^=b;
   b^=a;
   a^=b;
}
```
if u wanto swap integers , u should direct writing:
```
var a = 1,b=2;
a^=b;
b^=a;
a^=b;
console.log(a,b);
```

**Comment by johanneswilm** [comment] 2017-04-06 07:25
How about the ES2015 destructuring version?

    [a,b]=[b,a]

I guess the thing that is stopping us from using that is IE11 [1]?

[1] https://kangax.github.io/compat-table/es6/

**Comment by DemonCloud** [comment] 2017-04-06 07:33
should support IE9+

**Comment by johanneswilm** [comment] 2017-04-06 07:49
IE8-10 ended its life cycle a year ago, right?

I am wondering if it would make sense to switch to a development model where we use the ES2015 features and then transpile back for older browsersand to make it more efficient in newer ones. Replacing forEach is certainly doable, but it's to the detriment of code readability (with loops inside of each other, etc.), which is somehat important if we want this to be maintainable in the long run.

What would you think about that?

**Comment by DemonCloud** [comment] 2017-04-06 08:15
I agree with most of your point.

**Comment by DemonCloud** [comment] 2017-04-06 08:15
I agree with most of your point.

**Comment by johanneswilm** [comment] 2017-04-06 08:19
@DemonCloud You live in China? Then probably you have dealt more with older IE versions? Is there any transpiler you guys usually use for this?

**Comment by DemonCloud** [comment] 2017-04-06 08:32
Yes~, I don't need to be dealt more with older IE(The company projects). 
But In my opinion, I think the project should focus on users, rather than allow users to make changes to the project(for example: update the browser support ES2015).
At least, I request project is compatible to the IE9+

https://github.com/DemonCloud/aix/blob/master/src/aix.js#L837
I use this project to parse html and render in the default view

**Comment by ansuz** [comment] 2017-04-06 08:32
@DemonCloud I wrote a quick test to see if nodejs exposes pointers in the way you describe, this was the result:

```
var X = {
    a: [1],
    b: [2]
};

var swap = function (x, a, b) {
    x[a] ^= x[b];
    x[b] ^= x[a];
    x[a] ^= x[b];
};

swap(X, 'a', 'b');
console.log(X); // { a: 2, b: 1}
```

It seems there's some loss of information as the arrays in my object are coerced to numbers.

This might be irrelevant to this particular codebase, but I'd still be careful in relying on this behaviour.

**Comment by DemonCloud** [comment] 2017-04-06 08:41
@ansuz 
Yes. I really dont know why javascript get this result...........

**Comment by johanneswilm** [comment] 2017-04-06 09:23
> I think the project should focus on users, rather than allow users to make changes to the project(

Right, we agree on that. It's just that outside of China, my understanding is that IE9 and IE10 are gone because Microsoft stopped delivering security updates for them a year ago. Of course, Chinese users are also important, but I have less experience with them. So I was wondering if Chinese web developers have a standard way of dealing with JavaScript libraries that are written for newer browsers.

If it's just one function, then it's not so difficult to deal with.

As for the forEach... does this also apply when calling them without creating a new `this`? Such as 

    theArray.forEach(item => doSomething(item));

I couldn't find any of thee tests doing that, and I wonder if transpilers such as browserify would not turn this into something like:

    var item, i;
    for(i=1;i<theArray.length;i++) {
        item = theArray[i];
        doSomething(item); 
    }

If one of the transpilers is doing that, we could have both a readable codebase + quick execution speed + support for old browsers.

**Comment by ansuz** [comment] 2017-04-06 09:38
What evidence is there to support that `forEach` and `swap` are the bottlenecks in diffDOM?

**Comment by johanneswilm** [comment] 2017-04-06 09:56
@ansuz: I manually replaced the first 7 occurences of forEach with for(...) with cached array length (there are 22 occurences altogether). Running the site integration test 10 times does indeed show a speed improvement of around 22%:

    >>> 293+286+284+304+271+267+242+274+241+252
    2714
    >>> 266+207+222+220+204+217+195+202+193+187
    2113
 
So yes, this may not be enoguh evidence that there IS a significant different overall, but it certainly points in that direction.

**Comment by DemonCloud** [comment] 2017-04-06 10:11
@ansuz  @johanneswilm 
forEach create self-block, and it will auto ignore `undefined` value(with filter).
So, ES5 most function is not the optimized target, ES2015 also.

The ES2015(ES6) poor performance relative to the ES5.
see this test, I think babel is also a not optimized target now (for the moment)
https://kpdecker.github.io/six-speed/

**Comment by ansuz** [comment] 2017-04-06 10:12
22% is pretty good :smile:

When we started using diffDOM in [CryptPad](https://cryptpad.fr/pad/), we were a little worried about performance, since diffDOM is in the middle of some very active code.

As it turned out, the processor spends a lot more time hashing and decrypting, and the DOM stuff is pretty cheap. Improvements with no regressions are always nice, of course. I wouldn't expect diffDOM to be a big problem unless you were using it for gaming with a very high framerate (which, I think, is not really what it was designed for).

**Comment by johanneswilm** [comment] 2017-04-06 12:40
@DemonCloud: Right, `forEach(function(...){...})` will create a self-block and a new `this`. But does the same apply to `forEach((...)=>{...})`? The second one does not create a new `this`, so I assume it will be less costly. Is that not so? I cannot find it among any of the tests.

**Comment by johanneswilm** [comment] 2017-04-06 13:16
I have now removed each forEach and also replaced the swap closure with a simple temporary variable. Running the same tests 10 times, I get : 

    >>> 224+187+177+214+174+206+170+190+192+178
    1912

Which would be a 29.5% speed improvement. However, this is just one test and I haven't factored in things like laptop temperature, etc. . It also seems like this is slightly harder to read. I would really like to go the other direcction: Use ES2015 throughout. But as I said, maybe this is possible if we use browserify with the babel ES2015 preset or some such combination. I have put it in a separate branch so that you guys can test it out before we decide on how to proceed with this.

@ansuz You are probably right that diffDOM isn't the bottleneck in most applications. We have already spent a lot fo time in speeding up diffDOM. Nevertheless, if we can get another ~30% speed improvement "for free", then it seems like that is at least worth considering.

**Comment by DemonCloud** [comment] 2017-04-07 00:34
@johanneswilm 
U can use `Object.freeze` to make **unchangeable Object** visit faster ( in Chrome V8);

see this test:
https://jsperf.com/freeze-vs-seal-vs-normal/3

**Comment by DemonCloud** [comment] 2017-04-13 17:11
Something error on rendering the `input` when `value` change!

see the example:
"|" mean cursor.

[ a|bc ]

when I type "a":
[ aabc| ]

the cursor this move to end!
I think that u should care about `defaultValue` and `value` in dom properties

see this link to re-show this bug (example-2):
https://demoncloud.github.io/aix/#introduce

**Comment by johanneswilm** [comment] 2017-04-13 17:15
@DemonCloud Is this directly related to diffDOM? diffDOm is not contenteditable/selection aware. This is one of the reasons Fidus Writer stopped using a DOm diffign approach for collaborative text editing. But it seems others have gotten this to work -- possibly by recording the selection before applying the change and reestablishing it later on (that's what we used to do). Maybe check with one of those projects?

**Comment by DemonCloud** [comment] 2017-04-13 18:35
@johanneswilm 
I got solution.  hack the change event, and store the cursor position.
diffDOM do not need care about this.

**Comment by johanneswilm** [comment] 2017-04-13 19:54
@DemonCloud You shouldn't need to "hack" any part of diffDOM. Just override the function that applies changes to text nodes [1]. This is where we used to have the logic that noted and then reapplied the caret position with some added intelligence.

[1] https://github.com/fiduswriter/diffDOM/blob/gh-pages/diffDOM.js#L413

**Comment by johanneswilm** [comment] 2017-07-02 04:17
> U can use `Object.freeze` to make **unchangeable Object** visit faster ( in Chrome V8);

@DemonCloud It looks like there was a performance increase in the versions 51-58 whjen using Object.freeze, but that the current version of Chrome is equally fast no matter whether usign freeze or not. I have experimented with adding it, but since it gives no improvement, I'll drop it again. Does that sound ok?

**Comment by johanneswilm** [comment] 2017-07-02 04:39
All the other issues here should be resolved and merged by now. Please reopen if needed.

**Closed by johanneswilm** 2017-07-02 04:39 UTC
