### ISSUE TITLE
Removing first child results in overly complicated diff

### ISSUE THREAD

**Issue by edg2s** [fiduswriter/diffDOM#47] opened 2016-07-15 10:41 UTC
Removing the last child node:
`<h1>Foo</h1><h2>Bar</h2><h3>Baz</h3>` to `<h1>Foo</h1><h2>Bar</h2>`

gives a nice clean diff:

`{"action":"removeElement","route":[2],"element":{"nodeName":"H3","childNodes":[...]}}`

Removing the first child node:
`<h1>Foo</h1><h2>Bar</h2><h3>Baz</h3>` to `<h2>Bar</h2><h3>Baz</h3>`

gives a massive diff:

```
{"action":"replaceElement","oldValue":{"nodeName":"H1","childNodes":[...]},"newValue":{"nodeName":"H2","childNodes":[...]},"route":[0]},
{"action":"replaceElement","oldValue":{"nodeName":"H2","childNodes":[...]},"newValue":{"nodeName":"H3","childNodes":[...]},"route":[1]},
{"action":"removeElement","route":[2],"element":{"nodeName":"H3","childNodes":[...]}}
```

**Comment by johanneswilm** [comment] 2016-07-15 11:25
Hey @edg2s, 
thanks for your reports! I have added a fix for #46, but after fixing #46, I cannot reproduce this issue. I have added the example you mention to the top of the basic.html file and as far as I can tell, it only produces one diff.

**Comment by edg2s** [comment] 2016-07-15 12:21
The example you added was removing the <h3>, the problem diff is when you remove <h1>. I think this is the same problem as this: https://facebook.github.io/react/docs/reconciliation.html#problematic-case - they work around it by letting you set a key or id attribute.

**Comment by johanneswilm** [comment] 2016-07-15 12:30
Ah sorry, I see now. Well there have hundreds of issues where the diff wasn't of the perfect length, so the current algorithm is a compromise between these. We are pretty good right now, but there is probably still room for improvement. We have applied a number of patches that have tried to improve the situation, and the risk is always that if you improve it for one case, another case will get worse.

So this isn't high priority as it works (and it doesn't take a long time to apply 3 patches either). But if your time is willing to invest the time to test it and come up with an even better algorithm that works in even more cases, I'll be happy to apply such a patch.

Let me know if you will be working on this. Otherwise it won't be fixed, I am afraid.

**Comment by edg2s** [comment] 2016-07-15 13:42
Not sure I know how to fix it other than that link I provided (using persistent keys), but the issue here is that if you remove a node from the tree, _all_ its subsequent siblings get re-rendered. Say you have a document which is made up for 100 sibling paragraphs and headings (a long article, for example), then deleting a paragraph near the top triggers the whole document to rebuild, which is pretty much the worst case for this algorithm.

**Comment by edg2s** [comment] 2016-07-15 13:45
I found this library https://github.com/nyxtom/reconcile.js which does persistence using ID attributes.

**Comment by johanneswilm** [comment] 2016-07-16 09:29
> Not sure I know how to fix it other than that link I provided (using persistent keys)

@edg2s When you refer to "that link I provided" you mean https://facebook.github.io/react/docs/reconciliation.html#problematic-case ? I can't find the word "persistent" on that page.

> but the issue here is that if you remove a node from the tree, all its subsequent siblings get re-rendered. 

I see. Additionally, the document order is mostly, but not always, the same as the rendering order.

This is not an area I have looked much at, but I wonder if it would be possible to use something like https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame to make sure that nothing is repainted before all diffs have been applied.

**Comment by johanneswilm** [comment] 2016-07-17 07:50
@edg2s Sorry, I realize now that you probably aren't as much concerned about repainting the page as putting overly large chunks into the DOM.

Quickly glancing at the source code of that library, it seems that only works if a particular node has an id attribute or if the tags are in the same order. Else  an ID will be assigned based on the tag name and a counter. 

So this should work:

```<h1>hello</h1><h2>fellow</h2><h3>mellow</h3>``` -> ```<h2>fellow</h2><h3>mellow</h3>``` 

But this would give problems:

```<h1>hello</h1><h1>fellow</h1><h3>mellow</h3>``` -> ```<h1>fellow</h1><h3>mellow</h3>``` 

A long document with lots of  ```<p></p>``` nodes, where the first paragraph is removed will therefore create similar issues. Maybe if one instead created an ID based on the tag name + a checksum calculated from the contents of that node it could work... or maybe that would be overly expensive.

There are always advantages and disadvantages to every approach. It sounds like you won't work on this, so it will just stay as it is for now.

**Comment by johanneswilm** [comment] 2016-07-17 08:22
@edg2s I looked over out code to see if there was an easy way to fix this particular case. It turned out that the group relocation code could take care of this particular case.

**Closed** 2016-07-17 08:23 UTC
