### ISSUE TITLE
Diff a detached node to an attached node.

### ISSUE THREAD

**Issue by treshugart** [fiduswriter/diffDOM#25] opened 2015-08-22 05:17 UTC
This is similar to #11.

My use case is I want to template a custom element. When state changes, I want to take the rendered HTML and diff it to what is currently there. The custom element may or may not be in the document at this point in time. The `diff()` function is causing errors when DOM mutations happen because it seems to be invoking `apply()`. From reading the documentation, it seems that it shouldn't be invoking `apply()` automatically, but instead leaving that up to the user. Heres a [JSBin](http://jsbin.com/quwezi/1) for it. 

In #11, you said:

> I would suggest you just filter out any changes on the top node.

I'm not sure what you mean by that, but I assume that I'd have to have a diff object in order to do that. Probably easy enough, but you also said:

> I don't see this being relevant enough as a feature.

You may be right in that it may not add that much convenience. I can't have much an opinion on the level of difficulty required to filter out any changes on the top node because I can't get there. However, I would think that making the API consumer mutate the diff object would be exposing an implementation detail that they shouldn't be concerned with. If this was a feature, it would probably allow the diffing between an actual `DocumentFragment` and a node in the DOM, which would potentially add a lot of convenience for some (me for sure).

Thanks for writing this. I'm excited to experiment with it given I can get past this hurdle.

**Comment by johanneswilm** [comment] 2015-08-22 18:13
> My use case is I want to template a custom element. [...] . Heres a [JSBin](http://jsbin.com/quwezi/1) for it. 

As far as I can tell according to createElement rules [1], you are trying to create a `HTMLUnknownElement`, which is described as "invalid HTML" [2], which is why there are lots of methods missing on that element. diffDom requires everythign you diff with it to be valid HTML. Why do you need to diff invalid HTML?

[1] https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement
[2] https://developer.mozilla.org/en-US/docs/Web/API/HTMLUnknownElement

**Comment by johanneswilm** [comment] 2015-08-22 18:17
> The diff() function is causing errors when DOM mutations happen because it seems to be invoking apply(). From reading the documentation, it seems that it shouldn't be invoking apply() automatically, but instead leaving that up to the user.

This is just about how the system works internally. It takes a copy of the element that you diff against and then looks for differences. Every time it finds one, it applies that to the copy it holds, until it can no longer find any differences. This is different from the "apply" mechanism you may want to call yourself at a later stage to apply the diff to another node.

As I can see nothing wrong here, I will close this bug. Please reopen if you continue to think there is a bug in diffDOM.

**Comment by treshugart** [comment] 2015-08-22 21:53
Hey, thanks for getting back to me. Responses below.

> As far as I can tell according to createElement rules [1], you are trying to create a HTMLUnknownElement, which is described as "invalid HTML" [2], which is why there are lots of methods missing on that element. diffDom requires everythign you diff with it to be valid HTML. Why do you need to diff invalid HTML?

`HTMLUnknownElement` is considered "invalid" but still derives from `HTMLElement` and therefore implements all of its methods and properties as stated on the page you linked. Valid elements that derive from `HTMLElement` seem to work, so nodes that simply implement only `HTMLElement` don't seem to work meaning this won't work for elements that actually do conform to the custom element spec even in native. See updated bin (http://jsbin.com/quwezi/10). This is a bug if you consider it working with the custom element spec important.

The other point I was trying to make is that since `diff()` calls `apply()`, when diffing detached nodes it tries to call `replaceChild` on an empty `parentNode`. In order to diff the content of two detached nodes I must compare each `childNode` separately, correct?

**Comment by johanneswilm** [comment] 2015-08-23 00:56
I see what you are saying. You are welcome to figure out why it's not working with your custom elements and write a patch for it. I'll merge if this is of sufficient interest also to others

As for the detached stuff: you are right, if they are entirely different element types, the patch should be to simply destroy the entire thing and create something entirely new. But because you have nowhere to connect that new thing to, it's giving an error. If you instead put the two elements inside a div each, also disconnected from the DOM, it is working. It shouldn't be too hard to write some code to do that correctly, I don't think. Also there you are welcome to supply patches.

**Comment by johanneswilm** [comment] 2015-08-23 07:05
@treshugart: On second thought, I think your issue with the custom elements really is a nonissue. custom elements are not a problem if you use them further down the tree: http://jsbin.com/cuyixu/1/edit?html,js,console,output

The problem is merely that you want to create a diff from one element to another element with a different type. AFAIK you can not actually change the element type of an element; you have to destroy it and create a new one. That's why the kind of diff you would be producing would not be usable, at least not using our apply function. The same happens if you have a \<p> and a \<div>.  The way our apply-function works is that you can say "please apply this diff A to this element B" (attached or not attached). But if the diff describes a totally different element type for the root element of the diff, then there is no way one can apply the diff to element B, right?

**Comment by treshugart** [comment] 2015-08-26 03:45
> On second thought, I think your issue with the custom elements really is a nonissue.

I'm reading my last comment and sort of chuckling to myself because I don't understand what I was trying to say. Sorry. I actually observed what you're saying here. I think what I was trying to say that even `HTMLUnknownElement`s should work, so therefore custom elements should work. And they do, as you've described. I was trying to diff whole nodes and only wanted the content diffed as you suspected.

> The problem is merely that you want to create a diff from one element to another element with a different type.

Yeah, that's correct. The use case is I am templating a custom element and I want to see the difference between the updated HTML and the custom element's current HTML rather than the custom element itself. The only way I see to do that would be to clone the element, reset innerHTML and then compare. Simply adding the HTML to a `<div>` or using a real `DocumentFragment` doesn't seem like it'd work with the current API.

> AFAIK you can not actually change the element type of an element

Yeah, that's correct.

> But if the diff describes a totally different element type for the root element of the diff, then there is no way one can apply the diff to element B, right?

It's possible to generate a diff between to disparate lists of elements, so one should be able to apply those instructions to an element in much the same way. I see three parts here:

1. Diff a single node.
2. Diff the content of a single node.
3. Diff a node and its content (reusing 1 and 2).

**Comment by johanneswilm** [comment] 2015-08-27 15:46
> Simply adding the HTML to a `<div>` or using a real DocumentFragment doesn't seem like it'd work with the current API.

@treshugart Not sure what you mean. The element type of the two elements you are trying to compare, has to be the same type, otherwise the diff would be unusable. So you get an error. It would probably be better if it would give you a more descriptive error message.

You can easily solve your problem by doing:

http://jsbin.com/tacaludixu/1/edit?html,js,console,output


> It's possible to generate a diff between to disparate lists of elements, so one should be able to apply those instructions to an element in much the same way. I see three parts here:

> 1. Diff a single node.
> 2. Diff the content of a single node.
> 3. Diff a node and its content (reusing 1 and 2).

I am not sure we use the same definition of diff. Diff, for me, can only be a difference between two things. It's like direction: You cannot say in which direction Moscow is, if you don't know where your starting point it. So that kills all of those three examples.

**Comment by treshugart** [comment] 2015-08-28 00:57
> I am not sure we use the same definition of diff.

I'm certain we do. I'll try and clarify:

1. Diff node `a` excluding its tree **with** *node `b` excluding its tree*.
2. Diff the content of node `a` **with** *the content of node `b`*.
3. Diff node `a` and its content **with** *node `b` and its content* (combination of 1 and 2).

What `diffDOM` seems to do is number 3, but not 1 or 2. The JSBin you provided describes how you'd do number 2 using number 3. This won't work for me because my node `a` (the node I want to patch) is already in the DOM. If I were to wrap it with a node to emulate number 2, then it would be removed from the DOM and I'd have to reinsert it which sort of defeats the purpose of diffing in the first place. Cloning might work but then I'd be cloning an entire tree which could be expensive.

> The element type of the two elements you are trying to compare, has to be the same type, otherwise the diff would be unusable.

This is only true for number 1 and number 3, but not number 2.

I hope I've been able to clarify what I want to do. I haven't dug too much, but I don't think this would be a small change. It may not be a massive change, but it's more than a few LoC. It's up to you whether or not it's valuable for you. Feel free to close this issue if not.

**Comment by johanneswilm** [comment] 2015-08-28 07:33
> This won't work for me because my node a (the node I want to patch) is already in the DOM. 

Ok, then that is not what your JSBIN example shows, right?

If it already is in the DOM, and therefore has a parent node, then you shouldn't have any problems diffing with that node anyway.

Could you give a JSbin example of what exactly you are trying to do and why it's not working?

**Comment by johanneswilm** [comment] 2015-08-28 07:48
1. Diff node `a` excluding its tree **with** *node `b` excluding its tree*.

Is this not just comparing the attributes and the element Types? I don't think you need a library for that.

2 and 3 are no problem as long as the nodes have some kind of parent node OR are of the same element type. The one case which doesn't work is if they are BOTH of different element types AND of do not have parent nodes. This is not due to problems in diffDOM, but due to lack of the needed functions in JavaScript to change the type of an existing node.

**Closed** 2015-08-28 08:08 UTC
